/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */


#include "GestorBiblioteca.h"

TLibro *Biblioteca=NULL; //Vector dinámico de libros
int NumLibros=0; //Número de libros almacenados en el vector dinámico.
int Tama=0; //Tamaño del vector dinámico. El incremento será por bloques de 4 libros.
int IdAdmin=-1; //Identificador de Administración enviado al usuario.
Cadena NomFichero=""; //Nombre del último fichero binario que se ha cargado en memoria.
int CampoOrdenacion=0; //Campo de ordenación por que se ordenarán los libros.

bool_t EsMenor(int P1, int P2, int Campo)
{
	bool_t salida=FALSE;
	TLibro L1=Biblioteca[P1];
	TLibro L2=Biblioteca[P2];
	
	switch(Campo)
	{
		case 0: salida=strcmp(L1.Isbn,L2.Isbn)<0?TRUE:FALSE;
				break; 
		case 1: salida=strcmp(L1.Titulo,L2.Titulo)<0?TRUE:FALSE;
				break; 
		case 2: salida=strcmp(L1.Autor,L2.Autor)<0?TRUE:FALSE;
				break; 
		case 3: salida=L1.Anio<L2.Anio?TRUE:FALSE;
				break; 
		case 4: salida=strcmp(L1.Pais,L2.Pais)<0?TRUE:FALSE;
				break; 
		case 5: salida=strcmp(L1.Idioma,L2.Idioma)<0?TRUE:FALSE;
				break; 
		case 6: salida=L1.NoLibros<L2.NoLibros?TRUE:FALSE;
				break; 
		case 7: salida=L1.NoPrestados<L2.NoPrestados?TRUE:FALSE;
				break; 
		case 8: salida=L1.NoListaEspera<L2.NoListaEspera?TRUE:FALSE;
				break; 
	}
	return salida;
}

int *
conexion_1_svc(char *argp, struct svc_req *rqstp)
{
	static int result; // Importante que sea estática
	 
	// si idAdmin no es -1 significa que hay un usuario conectado
	if (IdAdmin != -1) {
        result = -1;
    }
	else if (strcmp(argp, "563498")!= 0) {
        result = -2; // Contraseña incorrecta
    }else {
        result = 1 + rand() % RAND_MAX; 
		IdAdmin = result; 
    }
	return &result;
}

bool_t *
desconexion_1_svc(int *argp, struct svc_req *rqstp)
{
	static bool_t  result;
	if(*argp != IdAdmin){
		result = 0;
		printf("Error: No autorizado\n");
	}
	else{
		IdAdmin = -1;
		result = 1;
	}

	return &result;
}

int *
cargardatos_1_svc(TFichero *argp, struct svc_req *rqstp)
{
	static int  result;
	
	if(argp->Ida!=IdAdmin){
		result =-1;
	}


	printf("cargar datos");
	fflush(stdout);
	FILE*fdatos=fopen(argp->NomFile,"r+b");
	if(fdatos==NULL){
	result=0;
	return &result;
	}
	fflush(stdout);
	fread(&NumLibros,sizeof(NumLibros),1,fdatos);
	printf("Hay %d libros en el documento",NumLibros);
	if(Biblioteca==NULL)
	Biblioteca=(TLibro*)calloc(NumLibros,sizeof(TLibro));
	else{
		free(Biblioteca);
		Biblioteca=(TLibro*)calloc(NumLibros,sizeof(TLibro));
	}
		

	for (int i=0;i<NumLibros;i++){
		TLibro LibroLeido;
		fread(&LibroLeido,sizeof(TLibro),1,fdatos);
		Biblioteca[i]=LibroLeido;

	}


	Tama=NumLibros;
	strcpy(NomFichero,argp->NomFile);
	printf( "El nombre del último fichero es %s",NomFichero);
	for(int i=0;i<NumLibros;i++){
		printf("Libro %d de nombre %s",i,Biblioteca[i].Titulo);
	}
	fclose(fdatos);
	result =1;
	return &result;
}


bool_t *
guardardatos_1_svc(int *argp, struct svc_req *rqstp)
{
	static bool_t result;
	if(*argp != IdAdmin){
		result = 0;
		printf("Error: No autorizado\n");
		return &result;
	}
	else{
		FILE *f_datos = fopen(NomFichero, "wb");
		if (f_datos == NULL)
		{
			result = 0;
			printf("Error al abrir el fichero para guardar los datos.\n");
			return &result;
		}
		fwrite(&NumLibros, sizeof(int), 1, f_datos);
		for(int i=0; i<NumLibros; i++)
		{
			fwrite(&Biblioteca[i], sizeof(TLibro), 1, f_datos);
		}
		fclose(f_datos);
		result = 1;
	}

	return &result;
}

int *
nuevolibro_1_svc(TNuevo *argp, struct svc_req *rqstp)
{
	static int result;

	if(argp->Ida != IdAdmin){
		result = -1;
		return &result;
	}
	else{
		
		int  busqueda = -1;
    for(int i = 0; i < NumLibros; i++) {
        if(strcmp(Biblioteca[i].Isbn, argp->Libro.Isbn) == 0) {
            busqueda = i;
            break;
        }
    }
	if(busqueda!=-1)
		result= 0;
	else{
		if (NumLibros >= Tama)
		{
			Tama += 4;
			Biblioteca = realloc(Biblioteca, Tama * sizeof(TLibro));
		}
		Biblioteca[NumLibros] = argp->Libro;
		NumLibros++;
		result = 1;
	}
	}
	return &result;
}

int *
comprar_1_svc(TComRet *argp, struct svc_req *rqstp)
{
	static int result;

	if(argp->Ida != IdAdmin){
		result = -1;
		return &result;
	}
	else{
		int pos = -1;
		for(int i=0; i<NumLibros; i++){
			if(strcmp(Biblioteca[i].Isbn, argp->Isbn) == 0){
				pos = i;
				break;
			}
		}
		if(pos == -1){
			result = 0; // Libro no encontrado	
		}
		else{
			Biblioteca[pos].NoLibros+= argp->NoLibros;
			if(Biblioteca[pos].NoListaEspera>0){
				if(Biblioteca[pos].NoListaEspera<=Biblioteca[pos].NoLibros){
					Biblioteca[pos].NoLibros+= Biblioteca[pos].NoLibros-Biblioteca[pos].NoListaEspera;
					Biblioteca[pos].NoPrestados+=Biblioteca[pos].NoListaEspera;
					Biblioteca[pos].NoListaEspera=0;
				}
				else{
					Biblioteca[pos].NoListaEspera-=Biblioteca[pos].NoLibros;
					Biblioteca[pos].NoPrestados+=Biblioteca[pos].NoLibros;
					Biblioteca[pos].NoLibros=0;
				}
			}
			
			result = 1;
			
		}
	}


	return &result;
}

int *
retirar_1_svc(TComRet *argp, struct svc_req *rqstp)
{
    static int result;

    if(argp->Ida != IdAdmin) {
        result = -1;
        return &result;
    }

    int pos = -1;
    for(int i = 0; i < NumLibros; i++) {
        if(strcmp(Biblioteca[i].Isbn, argp->Isbn) == 0) {
            pos = i;
            break;
        }
    }

    if(pos == -1) {
        result = 0;
    } else {
        if (Biblioteca[pos].NoLibros >= argp->NoLibros) {
            Biblioteca[pos].NoLibros -= argp->NoLibros;
            result = 1;
        } else {
            result = 2; 
        }
    }
	return &result;
}
bool_t *
ordenar_1_svc(TOrdenacion *argp, struct svc_req *rqstp)
{

	CampoOrdenacion=argp->Campo;
    static bool_t result;
    TLibro aux;

    if(argp->Ida != IdAdmin) {
        result = 0;
        return &result;
    }

    for(int i = 0; i < NumLibros - 1; i++) {
        for(int j = i + 1; j < NumLibros; j++) {
            if(EsMenor(j, i, CampoOrdenacion)) {
                aux = Biblioteca[i];
                Biblioteca[i] = Biblioteca[j];
                Biblioteca[j] = aux;
            }
        }
    }
    
    result = 1;
    return &result;
}

int *
nlibros_1_svc(int *argp, struct svc_req *rqstp)
{
	static int result;

	result = NumLibros;

	return &result;
}

int *
buscar_1_svc(TConsulta *argp, struct svc_req *rqstp)
{
    static int result;

    if(argp->Ida != IdAdmin) {
        result = -2;
        return &result;
    }

    
	 result=-1;
    for(int i = 0; i < NumLibros; i++) {
        if(strcmp(Biblioteca[i].Isbn, argp->Isbn) == 0) {
            result = i;
            break;
        }
    }


    return &result;
}

TLibro *
descargar_1_svc(TPosicion *argp, struct svc_req *rqstp)
{
	static TLibro result;

		if(argp->Pos>=NumLibros|| argp==NULL){
		strcpy(result.Titulo,"????");
		strcpy(result.Autor,"????");
		strcpy(result.Idioma,"????");
		strcpy(result.Isbn,"????");
		strcpy(result.Pais,"????");
		result.Anio=0;
		result.NoLibros=0;
		result.NoListaEspera=0;
		result.NoPrestados=0;
		}
		else{
		result = Biblioteca[argp->Pos];	
		printf("Libro descargado: %s", result.Titulo);
		}

	return &result;
}

int *
prestar_1_svc(TPosicion *argp, struct svc_req *rqstp)
{
    static int result;


    if(argp->Pos >= 0 && argp->Pos < NumLibros) {
        if(Biblioteca[argp->Pos].NoLibros > 0) {
            Biblioteca[argp->Pos].NoLibros--;
            Biblioteca[argp->Pos].NoPrestados++;
            result = 1;
        } else {
            Biblioteca[argp->Pos].NoListaEspera++;
            result = 0;
        }
    } else {
        result = -1;
    }

    return &result;
}

int *
devolver_1_svc(TPosicion *argp, struct svc_req *rqstp)
{
    static int result;

    if(argp->Pos >= 0 && argp->Pos < NumLibros) {
        if(Biblioteca[argp->Pos].NoPrestados > 0) {
            if(Biblioteca[argp->Pos].NoListaEspera > 0) {
                Biblioteca[argp->Pos].NoListaEspera--;
				result =0;
            } else {
                Biblioteca[argp->Pos].NoLibros++;
                Biblioteca[argp->Pos].NoPrestados--;
				result =1;
            }
            
        }else{
			result =2;
		}
    } else {
            result = -1;
        }

    return &result;
}
