/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "GestorBiblioteca.h"


TLibro *Biblioteca=NULL; //Vector dinámico de libros
int NumLibros=0; //Número de libros almacenados en el vector dinámico.
int Tama=0; //Tamaño del vector dinámico. El incremento será por bloques de 4 libros.
int IdAdmin=-1; //Identificador de Administración enviado al usuario.
Cadena NomFichero=""; //Nombre del último fichero binario que se ha cargado en memoria.
int CampoOrdenacion=0;



int *
conexion_1_svc(char *argp, struct svc_req *rqstp)
{

	static int  result;
		printf("conexion " );
	fflush(stdout);
		printf(argp);
	fflush(stdout);



	if (IdAdmin !=-1){
		result=-1;
	}

	else if (strcmp(argp,"123")==0){//Uso para pruebas la ocntraseña 123
	//printf("Hola, %s",*argp);
	
	result =1+rand()%RAND_MAX;
	IdAdmin=result;
	}
	else{
		result =-2;
	}
	 printf("Resultado de conexion_1: %d\n", result);//mostramos para saber si realmente funció
	return &result;
}

bool_t *
desconexion_1_svc(int *argp, struct svc_req *rqstp)
{
	static bool_t  result;
	
	printf("desconexion");
	fflush(stdout);

	return &result;
}

int *
cargardatos_1_svc(TFichero *argp, struct svc_req *rqstp)
{
	static int  result;
	
	printf("cargar datos");
	fflush(stdout);
	FILE*fdatos=fopen(argp->NomFile,"r+b");
	fflush(stdout);
	fread(&NumLibros,sizeof(NumLibros),1,fdatos);
	printf("Hay %d libros en el documento",NumLibros);
	if(Biblioteca==NULL)
	Biblioteca=(TLibro*)calloc(NumLibros,sizeof(TLibro));
	else{
		free(Biblioteca);
		Biblioteca=(TLibro*)calloc(NumLibros,sizeof(TLibro));
	}
		

	for (int i=0;i<NumLibros;i++){
		TLibro LibroLeido;
		fread(&LibroLeido,sizeof(TLibro),1,fdatos);
		Biblioteca[i]=LibroLeido;

	}


	Tama=NumLibros;
	strcpy(NomFichero,argp->NomFile);
	printf( "El nombre del último fichero es %s",NomFichero);
	for(int i=0;i<NumLibros;i++){
		printf("Libro %d de nombre %s",i,Biblioteca[i].Titulo);
	}

	return &result;
}


bool_t *
guardardatos_1_svc(int *argp, struct svc_req *rqstp)
{
	static bool_t  result;
	printf("guardar");
	fflush(stdout);
		

	return &result;
}

int *
nuevolibro_1_svc(TNuevo *argp, struct svc_req *rqstp)
{
	static int  result;
	printf("NuevoLobro");
	fflush(stdout);

	/*
	 * insert server code here
	 */

	return &result;
}

int *
comprar_1_svc(TComRet *argp, struct svc_req *rqstp)
{
	static int  result;
		printf("compra");
	fflush(stdout);

	/*
	 * insert server code here
	 */

	return &result;
}

int *
retirar_1_svc(TComRet *argp, struct svc_req *rqstp)
{
	static int  result;
		printf("retirar");
	fflush(stdout);

	/*
	 * insert server code here
	 */

	return &result;
}

bool_t *
ordenar_1_svc(TOrdenacion *argp, struct svc_req *rqstp)
{
	static bool_t  result;


	/*
	 * insert server code here
	 */

	return &result;
}

int *
nlibros_1_svc(int *argp, struct svc_req *rqstp)
{
	static int  result;

	result=NumLibros;

	return &result;
}

int *
buscar_1_svc(TConsulta *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

TLibro *
descargar_1_svc(TPosicion *argp, struct svc_req *rqstp)
{
	static TLibro  result;
		if(Biblioteca==NULL){
		printf("No se han cargado los datos");
		return NULL;
		}
	else{
		result=Biblioteca[argp->Pos];
	}
	return &result;
}

int *
prestar_1_svc(TPosicion *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
devolver_1_svc(TPosicion *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

bool_t EsMenor(int P1, int P2, int Campo)
{
	bool_t salida=FALSE;
	TLibro L1=Biblioteca[P1];
	TLibro L2=Biblioteca[P2];
	
	switch(Campo)
	{
		case 0: salida=strcmp(L1.Isbn,L2.Isbn)<0?TRUE:FALSE;
				break; 
		case 1: salida=strcmp(L1.Titulo,L2.Titulo)<0?TRUE:FALSE;
				break; 
		case 2: salida=strcmp(L1.Autor,L2.Autor)<0?TRUE:FALSE;
				break; 
		case 3: salida=L1.Anio<L2.Anio?TRUE:FALSE;
				break; 
		case 4: salida=strcmp(L1.Pais,L2.Pais)<0?TRUE:FALSE;
				break; 
		case 5: salida=strcmp(L1.Idioma,L2.Idioma)<0?TRUE:FALSE;
				break; 
		case 6: salida=L1.NoLibros<L2.NoLibros?TRUE:FALSE;
				break; 
		case 7: salida=L1.NoPrestados<L2.NoPrestados?TRUE:FALSE;
				break; 
		case 8: salida=L1.NoListaEspera<L2.NoListaEspera?TRUE:FALSE;
				break; 
	}
	return salida;
}
